paypal/paypal-sdk-constants

src/locale.js
Languages are now live in production.
Vietnam gains vi_VN as default
Romanian gets ro_RO as default, but will lose Rosetta Languages of es, fr, zh.
=> Add Romanian (ro_RO) and Vietnamese (vi_VN)

src/params.js
This `stage-alias` query param is a new feature for making it easier to test in our stage environment. It is not supported in production or sandbox. It's deigned to allow individual components to be overwritten similar to the local npm run alias feature. This will allow teams to test their specific components in Stage by passing the tarball(s) urls in the query string. Ex:
```
/sdk/js?
client-id=alc_client1&
components=messages&
stage-alias=https://uideploy--staticcontent--nate_test_4--ghe.preview.dev.paypalinc.com/upstream/bizcomponents/stage/package.tgz
```
=> Add stage-alias query param

src/params.js
This PR adds two new params for making it easier to test the JS SDK in stage. Note that these new parameters are not designed to work in production, only stage.
1. **cdn-registry** - this param will be used to override the default cdn registry url with the one defined in the query string. Ex: 
```
https://localhost.paypal.com:8443/sdk/js?
client-id=alc_client1&
cdn-registry=https://uideploy--staticcontent--970c7deca4c0f--ghe.preview.dev.paypalinc.com/js-sdk-release
```
2. **version** -  this param will be used to define the specific version based on the available ones defined in the dist-tags. Ex:
```
{
// available versions in dist-tags:
"name": "@paypal/sdk-release",
"dist-tags": {
"latest": "5.0.229",
"active-test": "5.0.227",
"active-local": "5.0.227",
"active-stage": "5.0.228", …
```
=> Add params for cdn-registry and version

src/funding.js, src/types.js
This PR adds `variant` and `paylater` types and removes `FLEX` const. Not yet returned from GraphQL but will be soon.
=> Update paylater types

src/error.js, src/index.js
This constant is meant to be used both with checkount-components and smart-payment-buttons for client-side validation errors.
=> Add constant for validation_error

src/params.js
We'd like to add a new global sdk flag for when popups are not available, e.g. `<script src="..." data-popups-disabled />` The global setting can be shared by the Buttons component and other components. 
This new flag will be set by the merchant and will help support devices that do not support popups like Desktop applications with embedded browsers.
=> Add sdk script setting for disabling popups

.flowconfig, package.json
This PR fixes the following flow error
https://github.com/paypal/paypal-sdk-constants/pull/72/checks#step:6:82
```
Error --------------------------------------- node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1
Unexpected end of input, expected the token `}`
2|
Found 1 error
```
=> Fix flow error with `resolve` sub dependency

package.json
this project doesn't use cross-domain-utils
=> remove cross-domain-utils

dist/module/funding.js, src/funding.js, src/types.js
Changed boleto to boletobancario
https://engineering.paypalcorp.com/jira/browse/DTALTPAY-919
Naming convention for Boleto / Boletobancario changed to match that of the confirm-payment-source call (boletobancario).
=> fix: rename boleto to match confirm-funding-source

.eslintrc.js, .flowconfig, babel.config.json, package.json, webpack.config.js
[DTPPSDK-935](https://engineering.paypalcorp.com/jira/browse/DTPPSDK-935)
* Migrated to grumbler scripts v8.  
* Added `flow-typed` and `cross-env` as explicit dev-dependencies.
=> feat: upgrade to grumbler scripts 8

src/params.js
This is to support the new displayOnly config option.
```
paypal.Buttons({
displayOnly: ["vaultable"]
})
```
=> Add New displayOnly Values

src/params.js
Adds the constant for SDK token data atrribute, we will guard usage in SDK client for any alpha features using it
=> Add SDK token to SDK settings constant

src/params.js
This PR adds a new component `hosted-buttons` so that we can load the SDK with a specific component namespace: `?components=hosted-buttons` 
As of today, we are loading the hosted-buttons component under the existing `buttons` component, but want to split it out into its own component so that we can add features without increasing the existing `buttons` bundle size.
=> Add hosted-buttons component

src/fpti.js
This PR adds a new key `referrer_domain` that will be used with FPTI and `xprops.referrerDomain`.
I added this new key next to the existing `REFERER` key to explicitly call out that there are two different keys that are related to referrer. The existing `REFERER` is used [here](https://github.com/paypal/paypal-smart-payment-buttons/blob/c268be3d0b18ff0ecaa11df646e74c8787ec03ff/src/lib/logger.js#L133) but does not send the correct URL. The analytics team would like to keep both of these keys (`referer_url` and `referrer_domain`). 
- https://github.com/paypal/paypal-checkout-components/pull/2296
- pass `xprops.referrerDomain` to FPTI around here https://github.com/paypal/paypal-smart-payment-buttons/blob/c268be3d0b18ff0ecaa11df646e74c8787ec03ff/src/lib/logger.js#L133
=> add FPTI key for referrer_domain

src/funding.js
---
This PR to add new CARD type that is needed on unbranded DINERS enablement. As part of hosted-field requires this value to generate the funding eligibility for DINERS in another component. Due to missing DINERS in the constants, the funding eligibility did not generated correctly.
=> Adding DINERS

src/funding.js
Currently, MAESTRO card brand is not supported in SDK V2 (card fields). To enable the maestro-based transactions in SDK V2, it is added to funding.js.
=> Adding MAESTRO card brand to funding.js

src/apm.js, src/funding.js, src/types.js
The deprecated APMs - maxima, zimpler are added back to sync with other SDK components. These APMs will be removed from all the components together.
=> Adding deprecated APM - maxima, zimpler to funding.js

.flowconfig, src/fpti.js, src/params.js
We have decided on a new name for tracking library usage, thus this PR. Alphabetization is in a separate commit, so it's easier to see the core changes. The original PR is [here](https://github.com/paypal/paypal-sdk-constants/pull/140).
DTPPCPSDK-1482
=> Rename library enum

src/params.js
@gregjopa, @westeezy, and I had a solid chat about DTPPCPSDK-1482 where it was decided we'd remove `JS_SDK_LIBRARIES` from `@paypal/sdk-constants` and hardcode values. This was inspired by the difficulty of adding `@paypal/sdk-constants` as a dependency of `paypal-js`.
=> Remove JS_SDK_LIBRARIES

src/funding.js, src/types.js
EFTPOS is a card brand used predominantly in the AU country region, with dual card brands Visa/MC or standalone card brand. This change will enable the EFTPOS card brand support in the SDK and currently, we are working on alpha version testing.
EFTPOS wiki - https://en.wikipedia.org/wiki/EFTPOS
=> Enable eftpos card brand 

src/params.js
This constant will be used by `@paypal/sdk-client` to validate and load the NextGen SDK bridge used to communicate back to a merchant page running the NextGen SDK.
=> Added WEB_SDK_BRIDGE_PATH

src/fpti.js
Adding an additional FPTI key to use for logging the checkout app that is executing the sdk callbacks
=> Add FPTI key

src/funding.js
Add Carte Bancaire to the list of eligible vendors to support co-badged cards when trying to complete payment with this network.
=> Add Carte Bancaire to the list of eligible vendors

src/funding.js
**Description**
Currently, this constant is utilized in our gql API as well as the SDK FI eligibility logic. Due to pre-defined constraints around the string casing of the Card networks, we want to make the `cb_nationale` constant uniform across the unbranded flow.
=> feat: update the constant for cb nationale as per gql requirements
